const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    ignores: [
      'node_modules/**',
      'src/types/database.ts', // generated by `npm run db:types`
      'supabase/**', // Deno edge functions — different runtime/globals
      '*.config.js',
    ],
  },
  {
    rules: {
      // A web-HTML concern, not a React Native one: literal apostrophes/quotes
      // inside <Text> are fine and escaping them just hurts copy readability.
      'react/no-unescaped-entities': 'off',
    },
  },
]);
